### ISSUE TITLE
Raise an exception upon receiving a negative return code

### ISSUE THREAD

**Issue by marklit** [Apakottur/shpyx#11]
If a command fails and a negative return code is given, it might be worth providing some sort of string reference to the command. For instance, -15 is `SIGTERM`. 

Perhaps raising an Exception and printing that out would help users fail fast?

The x86 process error return codes for Linux are listed here under "Signal numbering for standard signals": https://man7.org/linux/man-pages/man7/signal.7.html

**Comment by Apakottur** [comment]
Thanks for taking the time to write the issue!

Just to make sure I understand correctly, consider the following example:

```python
try:
    result = shpyx.run("echo 'hi' && exit 15")
except RuntimeError as e:
    print(e)
```

As of now, the call to `shpyx.run` will raise a `RuntimeError` (by default the return code is checked to be `0`, this can be disabled with `verify_return_code=False`), and printing the exception will give:

```
The command 'echo 'hi' && exit 15' failed with return code 15.

Error output:

All output:
hi
```

We can modify this to be:
```
The command 'echo 'hi' && exit 15' failed with return code 15 (SIGTERM).

Error output:

All output:
hi
```

What do you think?

**Comment by marklit** [comment]
That would be perfect.

**Comment by Apakottur** [comment]
@marklit 
Here's a shot - https://github.com/Apakottur/shpyx/pull/14, can you try it out and let me know if it's doing the right thing?

**Comment by marklit** [comment]
Spot on. Thanks for getting that patch in so quickly.
